name: glados-checkin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  00 15 * * *
      # https://tool.lu/crontab/
  #watch:
  #    types: started

jobs:
  checkin:
    runs-on: ubuntu-latest
    #if: github.event.repository.owner.id == github.event.sender.id
    # https://p3terx.com/archives/github-actions-manual-trigger.html

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3

    - name: requirements
      run: |
        pip3 install -r requirements.txt
    - name: Checkin
      run: |
        python3 checkin.py
      env:
        EMAIL: ${{ secrets.EMAIL }}
        PASSWORD: ${{ secrets.PASSWORD }}
        POP3_SERVER: ${{ secrets.POP3_SERVER }}
